### ISSUE TITLE
Fix urlDecodeUni for unicode mapping

### ISSUE THREAD

**Issue by jptosso** [jptosso/coraza-waf#53]
Required by many CRS tests...

```
	if (Code >= 0 && Code <= 65535)  {
		hmap = utils.UnicodeMapping.At(Code)
	}
```

It's already implemented but should we load unicode mappings like modsecurity from a file or maybe hardcode the data?

**Comment by fzipi** [comment]
Reopening — this gap is real and now has a concrete, confirmed motivating case.

## Context

While triaging [corazawaf/libinjection-go#118](https://github.com/corazawaf/libinjection-go/issues/118) and [coreruleset/go-ftw#392](https://github.com/coreruleset/go-ftw/issues/392) (Coraza reporting fewer libinjection SQLi false positives than a ModSecurity v2 reference run on the same corpus), I traced the divergence to this exact gap:

- ModSecurity v2's `t:urlDecodeUni`, when `SecUnicodeMapFile unicode.mapping 20127` is configured (which the official CRS reference Docker image sets by default — `MODSEC_UNICODE_MAPPING=20127` in `apache/Dockerfile`), maps curly quotes/apostrophes straight to ASCII before libinjection ever runs: codepage `20127` contains `2018:27 2019:27 201a:2c 201c:22 201d:22 201e:22`.
- Coraza's `urlDecodeUni` (`internal/transformations/url_decode_uni.go:33-54`) has a dead TODO for exactly this lookup — `hmap` is hardcoded to `-1`, the codepage-mapping block is commented out, so it always falls through to the raw low-byte behavior instead.
- I confirmed this empirically by running the actual reference container twice (unicode map on vs. stripped out of `modsecurity.conf`) against the exact corpus payloads: with the map on, curly-quote sentences get folded to a literal `"` and flagged as SQLi (fingerprint `s&nof`); with it off, they pass through unflagged — matching Coraza's current behavior. Details in the go-ftw thread linked above.

So this isn't a libinjection version or dataset difference (as `go-ftw#392` originally suspected) — it's specifically this missing best-fit table, and it's the direct cause of a measurable FP-count mismatch in quantitative CRS testing.

## Open question from the original issue, still unresolved

Load mappings from a file (matching `SecUnicodeMapFile`'s configurability), or hardcode a table? Leaning toward: hardcode just the common codepage (20127/US-ASCII, ~40 entries — curly quotes, dashes, fullwidth ASCII) to close the gap that actually caused the FP mismatch, without taking on a new directive/config-file-loading surface for a feature most deployments won't otherwise touch.

**Comment by fzipi** [comment]
CC: @jptosso @M4tteoP @jcchavezs
